{
    "endpoint": "xxx.xxx.xxx",
    "step":60,
    "counterType":"GAUGE",
    "tags":"company=xxx,department=xxx,product=xxx",
    "request":[
        {
            "metric":"graph.http.health",
            "protocol":"http",
            "type":"semanteme",
            "url":"http://127.0.0.1:9966/health",
            "ping":"",
            "pong":"ok"
        },
        {
            "metric":"graph.tcp.health",
            "protocol":"tcp",
            "type":"semanteme",
            "ip":"127.0.0.1",
            "port":9966,
            "ping":"ruok",
            "pong":"imok"
        },
        {
            "metric":"graph.udp.health",
            "protocol":"udp",
            "type":"status",
            "ip":"127.0.0.1",
            "port":9966
        }
    ]
}
